
export const SAVE_USER_INFO = 'SAVE_USER_INFO'
export const LOADING_USER = 'LOADING_USER'

export const FETCH_INVENTORIES = 'FETCH_INVENTORIES'
export const ADD_NEW_INVENTORY = 'ADD_NEW_INVENTORY'
export const DELETE_INVENTORY = 'DELETE_INVENTORY'
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY'

export const FETCH_ORDERS = 'FETCH_ORDERS'
export const CANCEL_ORDER = 'CANCEL_ORDER'
export const APPROVE_ORDER = 'APPROVE_ORDER'