
export const SAVE_USER_INFO = 'SAVE_USER_INFO'
export const LOADING_USER = 'LOADING_USER'

export const FETCH_INVENTORIES = 'FETCH_INVENTORIES'
export const ADD_NEW_INVENTORY = 'ADD_NEW_INVENTORY'
export const DELETE_INVENTORY = 'DELETE_INVENTORY'