
export const vehicles = [
    {
        id: 11,
        title: "Nissan Maxima SV Premium",
        make: "Nissan",
        model: "Maxima",
        year: "2015",
        kilometers: 39000,
        bodyType: "sedan",
        engine: "V-6 cyl",
        transimission: "Dual-Clutch Automatic",
        exteriorColor: "Dark Grey",
        interiorColor: "Jet Black",
        fuelType: "Gasoline Fuel",
        price: 2800,
        extras: ["Security System", "Air Conditioning", "Alloy Wheels", "Anti-lock Brakes", "Anti-Theft", "Anti-Starter", "Dual Airbag", "Intermittent Wipers", "Keyless Entry", "Power Mirrors", "Power Seat", "Power Steering", "CD Player"]
    },
    {
        id: 12,
        title: "Toyota RAV4 Limited V4",
        make: "Toyota",
        model: "RAV4",
        year: "2014",
        kilometers: 29000,
        bodyType: "SUV",
        engine: "V-6 cyl",
        transimission: "Manual",
        exteriorColor: "White",
        interiorColor: "Black",
        fuelType: "Gasoline Fuel",
        price: 2100,
        extras: ["Security System", "Air Conditioning", "Alloy Wheels", "Anti-lock Brakes", "Anti-Theft", "Anti-Starter", "Dual Airbag", "Intermittent Wipers", "Keyless Entry", "Power Mirrors"]
    },
    {
        id: 13,
        title: "Mercedes-Benz CLA45 AMG",
        make: "Mercedes-Benz",
        model: "CLA45 AMG",
        year: "2017",
        kilometers: 15000,
        bodyType: "sedan",
        engine: "V-8 cyl",
        transimission: "Dual-Clutch Automatic",
        exteriorColor: "Grey",
        interiorColor: "Maroon",
        fuelType: "Gasoline Fuel",
        price: 1800,
        extras: ["Security System", "Air Conditioning", "Alloy Wheels", "Anti-lock Brakes", "Anti-Theft", "Anti-Starter", "Dual Airbag", "Intermittent Wipers", "Keyless Entry", "Power Mirrors", "Power Seat"]
    },
    {
        id: 14,
        title: "Audi S4 3.0L V6 Turbo",
        make: "Audi",
        model: "S4",
        year: "2014",
        kilometers: 10000,
        bodyType: "sedan",
        engine: "V-6 cyl",
        transimission: "Dual-Clutch Automatic",
        exteriorColor: "Dark Grey",
        interiorColor: "Jet Black",
        fuelType: "Gasoline Fuel",
        price: 2000,
        extras: ["Security System", "Air Conditioning", "Alloy Wheels", "Anti-lock Brakes", "Anti-Theft", "Anti-Starter", "Dual Airbag", "Power Mirrors", "Power Seat", "Power Steering", "CD Player"]
    },
    {
        id: 15,
        title: "Ferrari F430 483 HP",
        make: "Ferrari",
        model: "F430",
        year: "2013",
        kilometers: 19000,
        bodyType: "coupe",
        engine: "DOHC inline-6",
        transimission: "6-speed Manual",
        exteriorColor: "Black",
        interiorColor: "Jet Black",
        fuelType: "Gasoline Fuel",
        price: 3300,
        extras: ["Security System", "Air Conditioning", "Anti-Starter", "Dual Airbag", "Intermittent Wipers", "Keyless Entry", "Power Mirrors", "Power Seat", "Power Steering", "CD Player"]
    },
]